# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_xHeu31na-AnjGdlsb-jQYsUYBhEPSv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

!pip install kaggle

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d mlg-ulb/creditcardfraud
!unzip creditcardfraud.zip

data = pd.read_csv("creditcard.csv")
data.head()

data.head()

data.shape

data['Class'].value_counts()

X = data.drop("Class", axis=1)
y = data["Class"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt="d")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

metrics = ["Accuracy", "Precision", "Recall", "F1"]
values = [accuracy, precision, recall, f1]

plt.bar(metrics, values)
plt.title("Model Performance")
plt.show()

sns.countplot(x=data['Class'])
plt.title("Fraud vs Normal Transactions")
plt.show()

importances = model.feature_importances_

plt.plot(importances)
plt.title("Feature Importance")
plt.show()

plt.hist(data['Amount'], bins=50)
plt.title("Transaction Amount Distribution")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# 1. Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
fig, ax = plt.subplots(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", ax=ax)
ax.set_title("Confusion Matrix")
ax.set_xlabel("Predicted")
ax.set_ylabel("Actual")
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=300)
plt.close()

# 2. Metrics Bar
metrics = ["Accuracy", "Precision", "Recall", "F1"]
values = [accuracy, precision, recall, f1]
fig, ax = plt.subplots(figsize=(5,4))
ax.bar(metrics, values, color=["#2196F3","#4CAF50","#FF9800","#9C27B0"])
ax.set_ylim(0, 1.1)
ax.set_title("Model Performance")
plt.tight_layout()
plt.savefig("metrics_bar.png", dpi=300)
plt.close()

# 3. Class Distribution
fig, ax = plt.subplots(figsize=(5,4))
sns.countplot(x=data['Class'], ax=ax)
ax.set_title("Fraud vs Normal Transactions")
plt.tight_layout()
plt.savefig("class_distribution.png", dpi=300)
plt.close()

# 4. Feature Importance
fig, ax = plt.subplots(figsize=(5,4))
ax.plot(model.feature_importances_)
ax.set_title("Feature Importance")
ax.set_xlabel("Feature Index")
ax.set_ylabel("Importance")
plt.tight_layout()
plt.savefig("feature_importance.png", dpi=300)
plt.close()

print("All 4 images saved!")